
CREATE TABLE TB_CIDADE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME varchar(100) NOT NULL,
    ESTADO char(2) NOT NULL ,
    PRIMARY KEY ( ID )
) ENGINE = innodb;


CREATE TABLE TB_ENDERECO(
    ID INT NOT NULL AUTO_INCREMENT,
    RUA varchar(255) NOT NULL ,
    BAIRRO varchar(50) NOT NULL ,
    NUMERO varchar(50) NOT NULL ,
	COMPLEMENTO varchar(100) NOT NULL,
	CEP varchar(10) NOT NULL,
	TB_CIDADE_ID INT NOT NULL,
	TIPO_ENDERECO INT NOT NULL CHECK (TIPO_ENDERECO BETWEEN 1 and 3),
	PRIMARY KEY ( ID ),
	CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (TB_CIDADE_ID) REFERENCES TB_CIDADE(ID)
) ENGINE = innodb;


CREATE TABLE TB_CLIENTE(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME varchar(150) NOT NULL ,
    RG varchar(150) NOT NULL ,
    CPF varchar(150) NOT NULL ,
	DATA_NASCIMENTO date NOT NULL,
	TELEFONE varchar(150) NOT NULL,
	EMAIL_ varchar(150) NOT NULL,
	COD_EMPRESA INT NOT NULL CHECK (COD_EMPRESA BETWEEN 1 and 2),
    PRIMARY KEY ( ID )
) ENGINE = innodb;


CREATE TABLE TB_CLIENTE_ENDERECO(
	TB_CLIENTE_ID INT NOT NULL,
    TB_ENDERECO_ID INT NOT NULL,
    PRIMARY KEY (TB_CLIENTE_ID, TB_ENDERECO_ID),
	CONSTRAINT FK_CLIENTE_ENDERECO_CLIENTE FOREIGN KEY (TB_CLIENTE_ID) REFERENCES TB_CLIENTE(ID),
	CONSTRAINT FK_CLIENTE_ENDERECO_ENDERECO FOREIGN KEY (TB_ENDERECO_ID) REFERENCES TB_ENDERECO(ID) ON DELETE CASCADE
) ENGINE = innodb;

